In [96]:
import pandas as pd
import numpy as np
from pathlib import Path
import os

In [79]:
def load_raw_data(raw_data_path:Path, year_lower_bound:int) -> pd.DataFrame:
    raw_dfs = []

    for csv in sorted(os.listdir(raw_data_path)):
        if csv == ".gitkeep":
            continue
        
        if int(csv.split(".")[0]) >= year_lower_bound:
            raw_dfs.append(pd.read_csv(raw_data_path / csv))

    return pd.concat(raw_dfs)

# Load in raw_data
raw_df = load_raw_data(raw_data_path = Path.cwd()/"data"/"raw", year_lower_bound = 2000)

In [80]:
# Look at 5 random rows
raw_df.sample(5)

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
700,2022-0404,Indian Wells Masters,Hard,128,M,20220307,252,144750,30.0,NaN,...,52.0,38.0,19.0,14.0,7.0,10.0,32.0,1393.0,82.0,781.0
753,2005-352,Paris Masters,Carpet,48,M,20051031,30,104068,12.0,NaN,...,42.0,38.0,22.0,14.0,2.0,5.0,18.0,1460.0,35.0,905.0
20,2014-339,Brisbane,Hard,28,A,20131229,21,103819,1.0,NaN,...,30.0,16.0,7.0,7.0,4.0,9.0,6.0,4205.0,61.0,774.0
243,2021-0321,Stuttgart,Grass,32,A,20210607,287,105023,NaN,NaN,...,47.0,34.0,14.0,11.0,1.0,3.0,67.0,1023.0,101.0,794.0
2937,2013-605,Tour Finals,Hard,8,F,20131104,513,104925,2.0,NaN,...,34.0,21.0,11.0,9.0,6.0,10.0,2.0,10610.0,8.0,3330.0

In [81]:
# Look at all columns -> `data_dictionary.txt` has column definitions
raw_df.columns

Index(['tourney_id', 'tourney_name', 'surface', 'draw_size', 'tourney_level',
       'tourney_date', 'match_num', 'winner_id', 'winner_seed', 'winner_entry',
       'winner_name', 'winner_hand', 'winner_ht', 'winner_ioc', 'winner_age',
       'loser_id', 'loser_seed', 'loser_entry', 'loser_name', 'loser_hand',
       'loser_ht', 'loser_ioc', 'loser_age', 'score', 'best_of', 'round',
       'minutes', 'w_ace', 'w_df', 'w_svpt', 'w_1stIn', 'w_1stWon', 'w_2ndWon',
       'w_SvGms', 'w_bpSaved', 'w_bpFaced', 'l_ace', 'l_df', 'l_svpt',
       'l_1stIn', 'l_1stWon', 'l_2ndWon', 'l_SvGms', 'l_bpSaved', 'l_bpFaced',
       'winner_rank', 'winner_rank_points', 'loser_rank', 'loser_rank_points'],
      dtype='object')

In [82]:
# Filter out all Davis Cup matches -> only care about ATP, Slams, Olympics
raw_df = raw_df[~raw_df["tourney_name"].str.contains("Davis Cup")]

In [106]:
# Fix tourney_date dtype
raw_df["tourney_date"] = pd.to_datetime(raw_df["tourney_date"])

In [ ]:
# Check tourney level -> all look good
raw_df["tourney_level"].unique()

array(['A', 'M', 'G', 'F', 'O'], dtype=object)

In [117]:
raw_df["score"].str.split(" ")

0                  [7-5, 4-6, 7-5]
1                       [7-5, 7-5]
2                       [6-3, 6-1]
3                       [6-4, 6-4]
4               [0-6, 7-6(7), 6-1]
                   ...
2811    [1-4, 4-2, 4-3(6), 4-3(5)]
2812    [2-4, 4-3(5), 4-3(4), 4-2]
2813    [4-3(3), 2-4, 4-1, 4-3(5)]
2814       [3-4(4), 4-2, 4-2, 4-1]
2815    [3-4(2), 4-3(7), 4-2, 4-2]
Name: score, Length: 67919, dtype: object

In [121]:
raw_df["winner_rank"]

0        11.0
1       211.0
2        48.0
3        45.0
4       167.0
        ...
2811     41.0
2812     41.0
2813    128.0
2814    138.0
2815    128.0
Name: winner_rank, Length: 67919, dtype: float64

In [83]:
# Look at winner and loser hand unique values
raw_df["winner_hand"].unique(), raw_df["loser_hand"].unique()

(array(['R', 'L', 'U'], dtype=object),
 array(['L', 'R', 'U', 'A'], dtype=object))

In [84]:
# Check players who have U, A, and nan hand values
raw_df[raw_df["winner_hand"] == "U"]["winner_name"].unique() # Looks like generally unknown players
raw_df[raw_df["loser_hand"] == "A"]["loser_name"].unique() # Only two players -> map A to R (ambidextrous but assume typically use R hand)

array(['Luke Jensen', 'Rabie Chaki'], dtype=object)

In [85]:
raw_df["winner_ht"].unique(), raw_df["winner_ht"].dtype
raw_df[raw_df["winner_ht"].isna()]

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
188,2000-315,Newport,Grass,32,A,20000710,10,103162,NaN,NaN,...,26.0,18.0,16.0,9.0,4.0,8.0,169.0,219.0,123.0,311.0
452,2000-329,Tokyo,Hard,56,A,20001009,10,102808,NaN,Q,...,51.0,37.0,24.0,15.0,4.0,8.0,417.0,57.0,48.0,786.0
473,2000-329,Tokyo,Hard,56,A,20001009,31,102808,NaN,Q,...,40.0,23.0,8.0,9.0,7.0,11.0,417.0,57.0,97.0,431.0
600,2000-339,Adelaide,Hard,32,A,20000103,10,103162,NaN,WC,...,26.0,17.0,25.0,13.0,5.0,10.0,205.0,198.0,127.0,369.0
1658,2000-429,Stockholm,Hard,32,A,20001120,10,103158,NaN,Q,...,43.0,29.0,22.0,14.0,2.0,6.0,395.0,61.0,215.0,174.0
1663,2000-429,Stockholm,Hard,32,A,20001120,15,103751,NaN,WC,...,56.0,36.0,19.0,14.0,2.0,5.0,621.0,23.0,35.0,960.0
2741,2000-620,Brighton,Hard,32,A,20001120,11,104014,NaN,WC,...,43.0,28.0,11.0,10.0,7.0,9.0,424.0,55.0,92.0,433.0
2932,2001-890,Shanghai,Hard,32,A,20010917,10,103403,NaN,NaN,...,47.0,33.0,26.0,14.0,8.0,10.0,350.0,85.0,109.0,386.0
2943,2001-890,Shanghai,Hard,32,A,20010917,21,103403,NaN,NaN,...,51.0,34.0,11.0,14.0,5.0,13.0,350.0,85.0,506.0,41.0
240,2002-315,Newport,Grass,32,A,20020708,15,102902,NaN,WC,...,77.0,49.0,17.0,17.0,4.0,9.0,381.0,75.0,116.0,352.0
474,2002-329,Tokyo,Hard,56,A,20020930,16,102902,NaN,Q,...,63.0,43.0,23.0,17.0,1.0,4.0,316.0,91.0,59.0,654.0
699,2002-360,Casablanca,Clay,32,A,20020408,15,103007,NaN,WC,...,28.0,20.0,16.0,10.0,1.0,4.0,494.0,45.0,107.0,380.0
408,2003-321,Stuttgart,Clay,48,A,20030714,12,103948,NaN,WC,...,51.0,38.0,27.0,14.0,2.0,3.0,191.0,191.0,71.0,605.0
1874,2003-495,Dubai,Hard,32,A,20030224,2,103948,NaN,Q,...,3.0,3.0,1.0,1.0,0.0,0.0,217.0,147.0,145.0,257.0
2228,2003-540,Wimbledon,Grass,128,G,20030623,12,104014,NaN,WC,...,105.0,72.0,31.0,24.0,6.0,9.0,489.0,43.0,35.0,1001.0
191,2004-311,Queen's Club,Grass,56,A,20040607,21,103913,NaN,Q,...,48.0,40.0,12.0,12.0,1.0,2.0,866.0,10.0,17.0,1320.0
208,2004-311,Queen's Club,Grass,56,A,20040607,38,103913,NaN,Q,...,43.0,32.0,10.0,11.0,1.0,3.0,866.0,10.0,78.0,522.0
516,2004-329,Tokyo,Hard,48,A,20041004,11,103403,NaN,WC,...,40.0,19.0,3.0,8.0,4.0,9.0,329.0,89.0,336.0,86.0
1802,2004-468,Estoril,Clay,32,A,20040412,7,104383,NaN,WC,...,47.0,29.0,23.0,14.0,7.0,12.0,999.0,6.0,673.0,22.0
1925,2004-499,Delray Beach,Hard,32,A,20040913,6,103663,NaN,Q,...,29.0,19.0,7.0,8.0,1.0,4.0,238.0,155.0,158.0,265.0
2752,2004-747,Beijing,Hard,32,A,20040913,14,104294,NaN,WC,...,50.0,35.0,17.0,14.0,9.0,14.0,1095.0,4.0,308.0,103.0
2845,2004-890,Shanghai,Hard,32,A,20040927,14,103337,NaN,WC,...,48.0,37.0,14.0,13.0,2.0,4.0,646.0,23.0,125.0,341.0
515,2005-329,Tokyo,Hard,48,A,20051003,10,103403,NaN,WC,...,37.0,26.0,8.0,10.0,2.0,5.0,431.0,64.0,91.0,451.0
1954,2005-499,Delray Beach,Hard,32,A,20050131,3,104167,NaN,WC,...,64.0,50.0,22.0,16.0,6.0,10.0,365.0,82.0,106.0,407.0
1958,2005-499,Delray Beach,Hard,32,A,20050131,7,104261,NaN,Q,...,44.0,25.0,11.0,9.0,6.0,10.0,386.0,71.0,270.0,139.0
2777,2005-747,Beijing,Hard,32,A,20050912,4,103817,NaN,WC,...,36.0,28.0,10.0,9.0,5.0,7.0,401.0,71.0,574.0,37.0
761,2006-3465,Mumbai,Hard,32,A,20060925,7,103538,NaN,Q,...,37.0,23.0,5.0,8.0,3.0,7.0,414.0,74.0,424.0,71.0
774,2006-3465,Mumbai,Hard,32,A,20060925,20,103538,NaN,Q,...,51.0,42.0,13.0,12.0,2.0,2.0,414.0,74.0,73.0,550.0
838,2006-360,Casablanca,Clay,32,A,20060424,6,102630,NaN,Q,...,28.0,16.0,9.0,8.0,2.0,6.0,272.0,126.0,NaN,NaN
1771,2006-439,Umag,Clay,32,A,20060724,6,103702,NaN,Q,...,21.0,14.0,8.0,6.0,2.0,4.0,559.0,43.0,99.0,425.0
1922,2006-495,Dubai,Hard,32,A,20060227,2,103600,NaN,WC,...,40.0,23.0,8.0,10.0,3.0,10.0,488.0,49.0,NaN,NaN
1986,2006-499,Delray Beach,Hard,32,A,20060130,4,104167,NaN,Q,...,58.0,38.0,14.0,14.0,7.0,11.0,246.0,144.0,57.0,630.0
2814,2006-747,Beijing,Hard,32,A,20060911,15,104305,NaN,Q,...,60.0,36.0,8.0,11.0,3.0,8.0,481.0,55.0,484.0,55.0
494,2007-329,Tokyo,Hard,48,A,20071001,5,104305,NaN,Q,...,36.0,22.0,19.0,10.0,7.0,11.0,543.0,41.0,411.0,76.0
795,2007-360,Casablanca,Clay,32,A,20070423,2,102630,NaN,WC,...,24.0,12.0,12.0,7.0,2.0,6.0,524.0,48.0,460.0,64.0
318,2008-316,Bastad,Clay,28,A,20080707,12,104914,NaN,WC,...,61.0,37.0,7.0,10.0,8.0,11.0,543.0,44.0,125.0,390.0
454,2008-329,Tokyo,Hard,48,A,20080929,5,103763,NaN,Q,...,60.0,39.0,18.0,13.0,9.0,13.0,232.0,171.0,131.0,364.0
511,2008-3348,New Haven,Hard,48,A,20080817,15,104305,NaN,Q,...,33.0,19.0,13.0,12.0,4.0,10.0,434.0,66.0,293.0,123.0
527,2008-3348,New Haven,Hard,48,A,20080817,31,104305,NaN,Q,...,36.0,22.0,9.0,10.0,0.0,6.0,434.0,66.0,52.0,748.0
536,2008-3348,New Haven,Hard,48,A,20080817,40,104305,NaN,Q,...,46.0,37.0,16.0,15.0,0.0,3.0,434.0,66.0,14.0,1405.0
540,2008-3348,New Haven,Hard,48,A,20080817,44,104305,NaN,Q,...,48.0,31.0,24.0,16.0,5.0,10.0,434.0,66.0,32.0,965.0
1447,2008-425,Barcelona,Clay,56,A,20080428,24,103448,NaN,Q,...,44.0,31.0,20.0,14.0,2.0,5.0,237.0,163.0,124.0,363.0
2316,2008-568,St. Petersburg,Hard,32,A,20081020,6,105122,NaN,WC,...,42.0,32.0,18.0,14.0,0.0,2.0,664.0,31.0,228.0,176.0
849,2009-404,Indian Wells Masters,Hard,96,M,20090312,13,104167,NaN,Q,...,43.0,30.0,13.0,11.0,5.0,9.0,232.0,326.0,83.0,962.0
1342,2009-424,San Jose,Hard,32,A,20090209,8,104167,NaN,Q,...,57.0,45.0,21.0,16.0,1.0,2.0,270.0,269.0,44.0,1490.0
1354,2009-424,San Jose,Hard,32,A,20090209,20,104167,NaN,Q,...,47.0,38.0,15.0,14.0,2.0,6.0,270.0,269.0,662.0,58.0
345,2010-2276,Zagreb,Hard,32,A,20100201,10,104948,NaN,WC,...,51.0,42.0,11.0,12.0,11.0,13.0,544.0,49.0,176.0,277.0
1927,2010-316,Bastad,Clay,28,A,20100712,8,104914,NaN,Q,...,30.0,22.0,9.0,9.0,1.0,3.0,483.0,63.0,253.0,180.0
275,2011-5012,Johannesburg,Hard,32,A,20110131,2,104695,NaN,WC,...,50.0,39.0,15.0,14.0,0.0,2.0,261.0,177.0,133.0,428.0
1619,2011-440,s Hertogenbosch,Grass,32,A,20110612,9,105894,NaN,WC,...,40.0,31.0,13.0,10.0,3.0,5.0,234.0,210.0,56.0,874.0
2582,2011-341,Metz,Hard,28,A,20110919,9,104023,NaN,Q,...,35.0,21.0,19.0,11.0,2.0,7.0,364.0,116.0,98.0,575.0
2806,2011-429,Stockholm,Hard,28,A,20111017,8,104681,NaN,Q,...,59.0,42.0,17.0,14.0,4.0,6.0,253.0,191.0,276.0,176.0
542,2012-533,Sao Paulo,Clay,28,A,20120213,4,105894,NaN,WC,...,31.0,14.0,20.0,9.0,7.0,11.0,184.0,265.0,87.0,619.0
1058,2012-360,Casablanca,Clay,28,A,20120409,8,105300,NaN,Q,...,28.0,12.0,4.0,7.0,1.0,6.0,544.0,52.0,97.0,561.0
1067,2012-360,Casablanca,Clay,28,A,20120409,17,105300,NaN,Q,...,33.0,19.0,8.0,9.0,2.0,7.0,544.0,52.0,752.0,19.0
2571,2012-341,Metz,Hard,28,A,20120917,1,104256,NaN,Q,...,52.0,43.0,13.0,15.0,1.0,3.0,502.0,64.0,117.0,489.0
2447,2019-M014,Moscow,Hard,32,A,20191014,284,200553,NaN,WC,...,43.0,23.0,18.0,12.0,3.0,9.0,498.0,59.0,1491.0,2.0
2557,2024-9410,Almaty,Hard,28,A,20241014,362,211514,NaN,WC,...,51.0,34.0,13.0,11.0,6.0,9.0,458.0,91.0,133.0,452.0

In [86]:
raw_df["loser_ht"].unique(), raw_df["loser_ht"].dtype
raw_df[raw_df["loser_ht"].isna()] # Players without enough matches to have height data

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
97,2000-311,Queen's Club,Grass,56,A,20000612,5,102533,NaN,NaN,...,50.0,32.0,26.0,14.0,5.0,8.0,114.0,360.0,498.0,41.0
199,2000-315,Newport,Grass,32,A,20000710,21,101727,5.0,NaN,...,36.0,23.0,12.0,8.0,4.0,7.0,81.0,512.0,169.0,219.0
219,2000-316,Bastad,Clay,32,A,20000710,10,102104,NaN,NaN,...,21.0,9.0,11.0,7.0,2.0,8.0,122.0,312.0,566.0,28.0
286,2000-319,Kitzbuhel,Clay,48,A,20000724,15,103344,NaN,NaN,...,45.0,28.0,5.0,9.0,2.0,5.0,77.0,559.0,700.0,16.0
448,2000-329,Tokyo,Hard,56,A,20001009,6,102133,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,142.0,269.0,1351.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450,2022-0424,Dallas,Hard,32,A,20220207,276,105577,NaN,Q,...,28.0,14.0,2.0,6.0,3.0,8.0,150.0,454.0,NaN,NaN
80,2024-0336,Hong Kong,Hard,32,A,20240101,273,207518,6.0,NaN,...,46.0,32.0,16.0,11.0,5.0,8.0,27.0,1470.0,NaN,NaN
1296,2024-7694,Lyon,Clay,32,A,20240520,277,106415,NaN,NaN,...,27.0,15.0,6.0,6.0,6.0,11.0,72.0,741.0,316.0,166.0
2216,2024-560,Us Open,Hard,128,G,20240826,129,126128,NaN,NaN,...,73.0,45.0,15.0,15.0,9.0,14.0,57.0,910.0,1848.0,1.0
2546,2024-9410,Almaty,Hard,28,A,20241014,373,202103,4.0,NaN,...,46.0,33.0,14.0,11.0,2.0,4.0,31.0,1470.0,458.0,91.0

In [87]:
# Check if earlier match data dont' have heights for players that eventually
# get their heights recorded
def check_ht_rows(names, raw_df:pd.DataFrame = raw_df):
    for name in names:
        unique_ht_instances = raw_df[(
            (raw_df["loser_name"] == "Dejan Petrovic") | 
            (raw_df["loser_name"] == "Dejan Petrovic")
            )]["loser_ht"].unique().tolist()

        if len(unique_ht_instances) > 1:
            print(f"{name} has both na and recorded height in data:")
            print(unique_ht_instances)
        
    print("No rows found with height discrepancies.")

# Check for names with NA values for loser_ht
names = raw_df[raw_df["loser_ht"].isna()]["loser_name"].unique().tolist()
check_ht_rows(names = names)

# Check for names with NA values for winner_ht
names = raw_df[raw_df["winner_ht"].isna()]["winner_name"].unique().tolist()
check_ht_rows(names = names)

# There does not appear to be rows where ht is nan for a player and later
# defined for the same player

No rows found with height discrepancies.
No rows found with height discrepancies.

In [ ]:
math.floor(2.8)

2

In [ ]:
# Check what ages look like
raw_df["winner_age"].dtype, raw_df["winner_age"].unique()
raw_df["loser_age"].dtype, raw_df["loser_age"].unique()

# Age is a float but can probably just be an int
# To convert to an int, we need to round down -> 
# a person isn't considered their next age until their birthday
raw_df["winner_age"] = np.floor(raw_df["winner_age"]).astype(int)
raw_df["loser_age"] = np.floor(raw_df["loser_age"]).astype(int)

In [105]:
raw_df.columns

Index(['tourney_id', 'tourney_name', 'surface', 'draw_size', 'tourney_level',
       'tourney_date', 'match_num', 'winner_id', 'winner_seed', 'winner_entry',
       'winner_name', 'winner_hand', 'winner_ht', 'winner_ioc', 'winner_age',
       'loser_id', 'loser_seed', 'loser_entry', 'loser_name', 'loser_hand',
       'loser_ht', 'loser_ioc', 'loser_age', 'score', 'best_of', 'round',
       'minutes', 'w_ace', 'w_df', 'w_svpt', 'w_1stIn', 'w_1stWon', 'w_2ndWon',
       'w_SvGms', 'w_bpSaved', 'w_bpFaced', 'l_ace', 'l_df', 'l_svpt',
       'l_1stIn', 'l_1stWon', 'l_2ndWon', 'l_SvGms', 'l_bpSaved', 'l_bpFaced',
       'winner_rank', 'winner_rank_points', 'loser_rank', 'loser_rank_points'],
      dtype='object')

In [ ]:
# Create unseeded indicator column & fill NAs with 0
df1["winner_unseeded"] = df1["winner_seed"].isna().astype(int)
df1["loser_unseeded"] = df1["loser_seed"].isna().astype(int)
df1["winner_seed"] = df1["winner_seed"].fillna(0)
df1["loser_seed"] = df1["loser_seed"].fillna(0)